import type { ScreenDefinition, ScreenRenderKey } from "@/lib/types";

type RawScreen = [string, string, string, string, ScreenDefinition["module"], ScreenRenderKey, ScreenDefinition["prototype"], string?];

const rawScreens: RawScreen[] = [
  ["PA-001", "Overview", "Overview", "Login · logo del sidebar", "pack", "overview", "navigable"],
  ["PA-002", "Centro de atención", "Overview", "Overview › Ver todo", "system", "attention", "pattern"],
  ["PA-010", "Lista de packs", "Packs", "Menú › Packs", "pack", "pack-list", "navigable"],
  ["PA-011", "Detalle de pack", "Packs", "Lista › fila · Ctrl K", "pack", "pack-detail", "navigable"],
  ["PA-012", "Versión de pack", "Packs", "Detalle › Versiones", "pack", "pack-version", "navigable"],
  ["PA-013", "Editor de borrador de pack", "Packs", "Detalle › Continuar borrador", "pack", "pack-editor", "navigable", "J1"],
  ["PA-014", "Diff de pack", "Packs", "Detalle › Comparar · Publicar › paso 1", "pack", "pack-diff", "navigable", "J1"],
  ["PA-015", "Revisión de publicación", "Packs", "Editor › Publicar…", "pack", "publish-review", "navigable", "J1"],
  ["PA-016", "Vista previa de impacto", "Packs", "Publicación paso 3 · Deprecar · Menú Release", "release", "impact", "navigable", "J6"],
  ["PA-017", "Deprecar pack", "Packs", "Detalle › Deprecar v7", "pack", "deprecate", "navigable", "J6"],
  ["PA-020", "Lista de capabilities", "Capabilities", "Menú › Capabilities", "pack", "capabilities", "navigable"],
  ["PA-021", "Detalle de capability", "Capabilities", "Lista › fila · desde composición del pack", "pack", "capability-detail", "navigable"],
  ["PA-022", "Grafo de dependencias", "Capabilities", "Detalle › Dependencias › Grafo", "pack", "capability-detail", "navigable"],
  ["PA-023", "Compatibilidad", "Capabilities", "Detalle › Compatibilidad", "pack", "capability-detail", "pattern"],
  ["PA-030", "Lista de catálogos base", "Catálogos", "Menú › Catálogos base", "pack", "catalogs", "navigable"],
  ["PA-031", "Detalle de catálogo", "Catálogos", "Lista › fila", "pack", "catalog-detail", "navigable"],
  ["PA-032", "Editor de versión de catálogo", "Catálogos", "Detalle › Continuar borrador", "pack", "catalog-editor", "navigable"],
  ["PA-033", "Diff de catálogo", "Catálogos", "Detalle › Comparar v5 → v6", "pack", "catalog-editor", "pattern"],
  ["PA-034", "Panel de validación", "Transversal", "Cualquier editor › Validar · ícono de estado", "transversal", "validation", "navigable"],
  ["PA-040", "Lista de workflows", "Workflows", "Menú › Workflows", "rules", "artifact-list", "pattern"],
  ["PA-041", "Detalle de workflow", "Workflows", "Lista › fila · desde composición del pack", "rules", "artifact-detail", "pattern"],
  ["PA-042", "Editor de workflow", "Workflows", "Detalle › Continuar borrador", "rules", "workflow-editor", "navigable", "J3"],
  ["PA-043", "Vista previa de workflow", "Workflows", "Editor › Vista previa", "rules", "workflow-preview", "pattern"],
  ["PA-044", "Diff de workflow", "Workflows", "Detalle › Comparar v6 → v7", "rules", "workflow-diff", "pattern"],
  ["PA-050", "Lista de requisitos documentales", "Requisitos", "Menú › Requisitos › Lista", "rules", "artifact-list", "navigable"],
  ["PA-051", "Matriz de requisitos", "Requisitos", "Menú › Requisitos (vista por defecto)", "rules", "requirements-matrix", "navigable", "J4"],
  ["PA-052", "Editor de requisito", "Requisitos", "Matriz › celda · Lista › Crear", "rules", "requirement-editor", "navigable"],
  ["PA-053", "Detalle de requisito", "Requisitos", "Lista › fila", "rules", "artifact-detail", "pattern"],
  ["PA-060", "Lista de políticas de compliance", "Compliance", "Menú › Compliance", "rules", "artifact-list", "pattern"],
  ["PA-061", "Editor de política de compliance", "Compliance", "Lista › fila › Continuar borrador", "rules", "compliance-editor", "navigable"],
  ["PA-062", "Simulador de compliance", "Compliance", "Editor › Simular", "rules", "compliance-simulator", "navigable"],
  ["PA-063", "Detalle de política de compliance", "Compliance", "Lista › fila", "rules", "artifact-detail", "pattern"],
  ["PA-070", "Lista de políticas de comisión", "Comisiones", "Menú › Comisiones", "rules", "artifact-list", "pattern"],
  ["PA-071", "Detalle de política de comisión", "Comisiones", "Lista › fila · desde inspector", "rules", "artifact-detail", "navigable"],
  ["PA-072", "Editor de reglas de comisión", "Comisiones", "Detalle › Reglas y splits", "rules", "commission-editor", "navigable", "J2"],
  ["PA-073", "Editor de splits", "Comisiones", "Editor › panel derecho", "rules", "split-editor", "navigable", "J2"],
  ["PA-074", "Simulador de comisión", "Comisiones", "Detalle › Simulador · Inspector › Simular", "rules", "commission-simulator", "navigable"],
  ["PA-075", "Diff de política de comisión", "Comisiones", "Detalle › Diff v4 → v5", "rules", "commission-diff", "navigable"],
  ["PA-080", "Lista de automatizaciones", "Automatizaciones", "Menú › Automatizaciones", "rules", "artifact-list", "pattern"],
  ["PA-081", "Editor de automatización", "Automatizaciones", "Lista › fila › Continuar borrador", "rules", "automation-editor", "navigable", "J5"],
  ["PA-082", "Simulador de automatización", "Automatizaciones", "Editor › panel derecho › Simular", "rules", "automation-simulator", "navigable"],
  ["PA-083", "Detalle de automatización", "Automatizaciones", "Lista › fila", "rules", "artifact-detail", "pattern"],
  ["PA-090", "Lista de métricas", "Métricas", "Menú › Métricas", "rules", "artifact-list", "pattern"],
  ["PA-091", "Editor de métrica", "Métricas", "Lista › fila › Continuar borrador", "rules", "metric-editor", "navigable"],
  ["PA-092", "Lineage de métrica", "Métricas", "Editor › panel derecho", "rules", "metric-lineage", "navigable"],
  ["PA-093", "Detalle de métrica", "Métricas", "Lista › fila", "rules", "artifact-detail", "pattern"],
  ["PA-100", "Catálogo de conectores", "Integraciones", "Menú › Conectores", "release", "connectors", "navigable"],
  ["PA-101", "Detalle de conector", "Integraciones", "Catálogo › card", "release", "connector-detail", "navigable"],
  ["PA-102", "Feature flags", "Integraciones", "Menú › Feature flags", "release", "feature-flags", "navigable"],
  ["PA-110", "Lista de Extension Schemas", "Extensión", "Menú › Extension Schemas", "release", "schemas", "navigable"],
  ["PA-111", "Editor de schema", "Extensión", "Lista › fila", "release", "schema-editor", "navigable"],
  ["PA-112", "Vista previa de schema", "Extensión", "Editor › panel derecho", "release", "schema-preview", "navigable"],
  ["PA-113", "Diff de schema", "Extensión", "Editor › Comparar v2 → v3", "release", "schema-diff", "pattern"],
  ["PA-120", "Impacto de un cambio", "Release", "Menú › Impacto · acción rápida del Overview", "release", "impact", "navigable"],
  ["PA-121", "Lista de pilotos", "Release", "Menú › Pilotos y rollout", "release", "pilots", "navigable", "J7"],
  ["PA-122", "Detalle de piloto", "Release", "Lista › fila", "release", "pilot-detail", "navigable", "J7"],
  ["PA-123", "Crear piloto", "Release", "Lista › Crear piloto · Publicación › como piloto", "release", "pilot-create", "navigable", "J7"],
  ["PA-124", "Rollout", "Release", "Detalle de piloto › Etapas del rollout", "release", "rollout", "navigable", "J7"],
  ["PA-125", "Ambientes", "Release", "Menú › Ambientes", "release", "environments", "navigable", "J9"],
  ["PA-126", "Comparar ambientes", "Release", "Ambientes › Comparar Staging → Production", "release", "environment-compare", "navigable", "J9"],
  ["PA-127", "Promoción", "Release", "Ambientes › fila con diferencia › Promover", "release", "promotion", "navigable", "J9"],
  ["PA-130", "Buscar inmobiliaria", "Diagnóstico", "Menú › Tenants", "release", "tenants", "navigable", "J8"],
  ["PA-131", "Configuración de inmobiliaria", "Diagnóstico", "Buscar › fila", "release", "tenant-detail", "navigable", "J8"],
  ["PA-132", "Inspector de configuración efectiva", "Diagnóstico", "Configuración › Inspector · desde una política", "release", "effective-inspector", "navigable", "J8"],
  ["PA-140", "Registro de auditoría", "Gobierno", "Menú › Auditoría · pestaña de cada artefacto", "release", "audit", "navigable"],
  ["PA-141", "Detalle de auditoría", "Gobierno", "Registro › fila", "release", "audit-detail", "navigable"],
  ["PA-142", "Catálogo de correcciones", "Gobierno", "Menú › Correcciones · desde una inmobiliaria", "release", "corrections", "navigable", "J10"],
  ["PA-143", "Flujo de corrección", "Gobierno", "Catálogo › comando", "release", "correction-flow", "navigable", "J10"],
  ["PA-150", "Búsqueda global", "Sistema", "Ctrl K · barra superior", "system", "global-search", "navigable"],
  ["PA-151", "Historial de cambios de producto", "Sistema", "Overview › Lanzamientos · Auditoría › pestaña", "release", "product-history", "navigable"],
  ["PA-152", "Sin permiso", "Sistema", "Al intentar una acción restringida", "release", "no-permission", "navigable"],
  ["PA-153", "VersionHeader", "Transversal", "Encabezado de todo artefacto", "transversal", "version-header", "navigable"],
];

export const screenRegistry: ScreenDefinition[] = rawScreens.map(([id, title, group, entry, module, renderKey, prototype, journey]) => ({
  id: id as `PA-${number}`,
  title,
  group,
  entry,
  module,
  renderKey,
  prototype,
  route: routeFor(id),
  ...(journey ? { journey: journey as ScreenDefinition["journey"] } : {}),
}));

function routeFor(id: string): string {
  const routes: Record<string, string> = {
    "PA-001": "/",
    "PA-002": "/centro-de-atencion",
    "PA-010": "/packs",
    "PA-011": "/packs/argentina-base",
    "PA-012": "/packs/argentina-base/versiones/v8",
    "PA-013": "/packs/argentina-base/versiones/v8/editar",
    "PA-014": "/packs/argentina-base/versiones/v8/comparar",
    "PA-015": "/packs/argentina-base/versiones/v8/publicar",
    "PA-016": "/release/impacto/argentina-base-v8",
    "PA-017": "/packs/argentina-base/deprecar",
    "PA-020": "/capabilities",
    "PA-021": "/capabilities/maintenance",
    "PA-022": "/capabilities/maintenance/dependencias",
    "PA-023": "/capabilities/maintenance/compatibilidad",
    "PA-030": "/catalogos-base",
    "PA-031": "/catalogos-base/property-types",
    "PA-032": "/catalogos-base/property-types/versiones/v6/editar",
    "PA-033": "/catalogos-base/property-types/comparar",
    "PA-034": "/validacion",
    "PA-040": "/workflows",
    "PA-041": "/workflows/residential-sale",
    "PA-042": "/workflows/residential-sale/v7/editar",
    "PA-043": "/workflows/residential-sale/v7/previsualizar",
    "PA-044": "/workflows/residential-sale/comparar",
    "PA-050": "/requisitos",
    "PA-051": "/requisitos/matriz",
    "PA-052": "/requisitos/nuevo",
    "PA-053": "/requisitos/identity-document",
    "PA-060": "/compliance",
    "PA-061": "/compliance/kyc/editar",
    "PA-062": "/compliance/kyc/simular",
    "PA-063": "/compliance/kyc",
    "PA-070": "/comisiones",
    "PA-071": "/comisiones/sale-default",
    "PA-072": "/comisiones/sale-default/reglas",
    "PA-073": "/comisiones/sale-default/splits",
    "PA-074": "/comisiones/sale-default/simular",
    "PA-075": "/comisiones/sale-default/comparar",
    "PA-080": "/automatizaciones",
    "PA-081": "/automatizaciones/lead-routing/editar",
    "PA-082": "/automatizaciones/lead-routing/simular",
    "PA-083": "/automatizaciones/lead-routing",
    "PA-090": "/metricas",
    "PA-091": "/metricas/close-rate/editar",
    "PA-092": "/metricas/close-rate/lineage",
    "PA-093": "/metricas/close-rate",
    "PA-100": "/conectores",
    "PA-101": "/conectores/whatsapp",
    "PA-102": "/feature-flags",
    "PA-110": "/extension-schemas",
    "PA-111": "/extension-schemas/property/editar",
    "PA-112": "/extension-schemas/property/previsualizar",
    "PA-113": "/extension-schemas/property/comparar",
    "PA-120": "/release/impacto",
    "PA-121": "/release/pilotos",
    "PA-122": "/release/pilotos/rental-administration",
    "PA-123": "/release/pilotos/nuevo",
    "PA-124": "/release/pilotos/rental-administration/rollout",
    "PA-125": "/release/ambientes",
    "PA-126": "/release/ambientes/comparar",
    "PA-127": "/release/ambientes/promover",
    "PA-130": "/diagnostico/inmobiliarias",
    "PA-131": "/diagnostico/inmobiliarias/inmobiliaria-norte",
    "PA-132": "/diagnostico/inmobiliarias/inmobiliaria-norte/configuracion-efectiva",
    "PA-140": "/auditoria",
    "PA-141": "/auditoria/entry-2026-0910",
    "PA-142": "/correcciones",
    "PA-143": "/correcciones/reprocess-compliance",
    "PA-150": "/buscar",
    "PA-151": "/historial-producto",
    "PA-152": "/sin-permiso",
    "PA-153": "/version-header",
  };
  return routes[id] ?? "/";
}

export function getScreenById(id: string): ScreenDefinition | undefined {
  return screenRegistry.find((screen) => screen.id === id);
}

export function getScreenByRoute(pathname: string): ScreenDefinition | undefined {
  const normalized = pathname.replace(/\/$/, "") || "/";
  return screenRegistry.find((screen) => screen.route === normalized);
}

export const screenGroups = [...new Set(screenRegistry.map((screen) => screen.group))];
